const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");
const { initialize, oracledb } = require("./db");
require("dotenv").config();

const app = express();
app.use(cors());
app.use(bodyParser.json());

// Initialize DB pool
initialize();

// 🧾 CREATE TABLE (run once in SQL*Plus or SQL Developer)
/*
CREATE TABLE form_submissions (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  first_name VARCHAR2(50),
  last_name VARCHAR2(50),
  submission_date DATE,
  submission_time VARCHAR2(20),
  department VARCHAR2(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
*/

// 🔹 POST route — save data
app.post("/api/submit", async (req, res) => {
  const { firstName, lastName, date, time, department } = req.body;

  try {
    const conn = await oracledb.getConnection();
    const query = `
      INSERT INTO form_submissions (first_name, last_name, submission_date, submission_time, department)
      VALUES (:firstName, :lastName, TO_DATE(:date, 'YYYY-MM-DD'), :time, :department)
    `;
    await conn.execute(query, { firstName, lastName, date, time, department }, { autoCommit: true });
    await conn.close();

    res.status(200).send({ message: "Form submitted successfully!" });
  } catch (err) {
    console.error(err);
    res.status(500).send({ message: "Error saving data" });
  }
});

// 🔹 GET route — fetch today's data (00:00–23:59)
app.get("/api/today", async (req, res) => {
  try {
    const conn = await oracledb.getConnection();
    const query = `
      SELECT first_name, last_name, TO_CHAR(submission_date, 'YYYY-MM-DD') AS date, submission_time, department
      FROM form_submissions
      WHERE TRUNC(submission_date) = TRUNC(SYSDATE)
      ORDER BY created_at DESC
    `;
    const result = await conn.execute(query);
    await conn.close();

    res.json(result.rows.map(r => ({
      firstName: r[0],
      lastName: r[1],
      date: r[2],
      time: r[3],
      department: r[4],
    })));
  } catch (err) {
    console.error(err);
    res.status(500).send({ message: "Error fetching data" });
  }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Server running on port ${PORT}`));
